services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=apollo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - ./test_db/init:/docker-entrypoint-initdb.d
    secrets:
      - db-password
    ports:
      - "8005:5432"

secrets:
  db-password:
    file: test_db/password.txt
